name: RocketModFix.Unturned.Redist.Server-Preview

on:
  workflow_run:
    workflows: ["Update Unturned Redist for Server Preview"]
    types:
      - completed
  push:
    branches: [ master ]
    paths:
      - 'redist/redist-server-preview/**'

jobs:
  build:
    name: "RocketModFix.Unturned.Redist Pack for Server Preview"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      name: Setup .NET
      with:
        dotnet-version: 8.x

    - uses: nuget/setup-nuget@v2
      name: Setup NuGet
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}

    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: redist/redist-server-preview/RocketModFix.Unturned.Redist.Server-Preview.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
        