name: RocketModFix.Unturned.Redist.Matrix

on:
  # push:
  #   branches: [ master ]
  #   paths:
  #     - 'redist/redist-*/**'
  workflow_dispatch:
    inputs:
      variant:
        description: 'Which variant to update'
        required: true
        type: choice
        options:
          - all
          - client
          - client-preview
          - client-preview-old
          - client-preview-publicized
          - client-publicized
          - server
          - server-preview
          - server-preview-old
          - server-preview-publicized
          - server-publicized

jobs:
  build:
    name: "Build ${{ matrix.variant }}"
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        include:
          # Client variants
          - variant: "client"
            nuspec_path: "redist/redist-client/RocketModFix.Unturned.Redist.Client.nuspec"
            trigger_path: "redist/redist-client/**"
            workflow_trigger: "Update Unturned Redist for Client"
          - variant: "client-preview"
            nuspec_path: "redist/redist-client-preview/RocketModFix.Unturned.Redist.Client.nuspec"
            trigger_path: "redist/redist-client-preview/**"
            workflow_trigger: "Update Unturned Redist for Client Preview"
          - variant: "client-preview-old"
            nuspec_path: "redist/redist-client-preview-old/RocketModFix.Unturned.Redist.Client.nuspec"
            trigger_path: "redist/redist-client-preview-old/**"
            workflow_trigger: "Update Unturned Redist for Client Preview Old"
          - variant: "client-preview-publicized"
            nuspec_path: "redist/redist-client-preview-publicized/RocketModFix.Unturned.Redist.Client.nuspec"
            trigger_path: "redist/redist-client-preview-publicized/**"
            workflow_trigger: "Update Unturned Redist for Client Preview"
          - variant: "client-publicized"
            nuspec_path: "redist/redist-client-publicized/RocketModFix.Unturned.Redist.Client.nuspec"
            trigger_path: "redist/redist-client-publicized/**"
            workflow_trigger: "Update Unturned Redist for Client Publicized"
          
          # Server variants
          - variant: "server"
            nuspec_path: "redist/redist-server/RocketModFix.Unturned.Redist.Server.nuspec"
            trigger_path: "redist/redist-server/**"
            workflow_trigger: "Update Unturned Redist for Server"
          - variant: "server-preview"
            nuspec_path: "redist/redist-server-preview/RocketModFix.Unturned.Redist.Server.nuspec"
            trigger_path: "redist/redist-server-preview/**"
            workflow_trigger: "Update Unturned Redist for Server Preview"
          - variant: "server-preview-old"
            nuspec_path: "redist/redist-server-preview-old/RocketModFix.Unturned.Redist.Server.nuspec"
            trigger_path: "redist/redist-server-preview-old/**"
            workflow_trigger: "Update Unturned Redist for Server Preview Old"
          - variant: "server-preview-publicized"
            nuspec_path: "redist/redist-server-preview-publicized/RocketModFix.Unturned.Redist.Server.nuspec"
            trigger_path: "redist/redist-server-preview-publicized/**"
            workflow_trigger: "Update Unturned Redist for Server Preview"
          - variant: "server-publicized"
            nuspec_path: "redist/redist-server-publicized/RocketModFix.Unturned.Redist.Server.nuspec"
            trigger_path: "redist/redist-server-publicized/**"
            workflow_trigger: "Update Unturned Redist for Server Publicized"

    # Only run if this is a workflow_dispatch with a specific variant or "all", or if the path matches
    if: |
      github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.variant == 'all' || github.event.inputs.variant == matrix.variant) ||
      github.event_name == 'push' && contains(toJSON(github.event.commits[0].modified), matrix.trigger_path) ||
      github.event_name == 'workflow_run' && github.event.workflow_run.name == matrix.workflow_trigger

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: nuget/setup-nuget@v2
      name: Setup NuGet
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}

    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: ${{ matrix.nuspec_path }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true 