name: RocketModFix.Unturned.Redist.Client-Preview-Old

on:
  workflow_run:
    workflows: ["Update Unturned Redist for Client Preview Old"]
    types:
      - completed
  push:
    branches: [ master ]
    paths:
      - 'redist/redist-client-preview-old/**'
  workflow_dispatch:

jobs:
  build:
    name: "RocketModFix.Unturned.Redist Pack for Client Preview Old"
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - uses: nuget/setup-nuget@v2
      name: Setup NuGet
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}

    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: redist/redist-client-preview-old/RocketModFix.Unturned.Redist.Client-Preview.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
        