name: RocketModFix.Unturned.Redist.Client-Preview

on:
  workflow_run:
    workflows: ["Update Unturned Redist for Client Preview"]
    types:
      - completed
  push:
    branches: [ master ]
    paths:
      - 'redist/redist-client-preview/**'

jobs:
  build:
    name: "RocketModFix.Unturned.Redist Pack for Client Preview"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      name: Setup .NET
      with:
        dotnet-version: 8.x

    - uses: nuget/setup-nuget@v2
      name: Setup NuGet
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget-version: '5.x'

    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: redist/redist-client-preview/RocketModFix.Unturned.Redist.Client-Preview.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true