name: "Verify.Redist.Update"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'redist/**'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  verify:
    name: "Verify Redist Update"
    runs-on: ubuntu-latest
    env:
      ALLOW_AUTO_MERGE_REDIST_PR: ${{ vars.ALLOW_AUTO_MERGE_REDIST_PR }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate redist update
        run: |
          echo "🔍 Verifying redist update..."

          VARIANT=$(echo "${GITHUB_HEAD_REF}" | cut -d'/' -f2 | sed -E 's/-[0-9]{8}-[0-9]{6}$//')
          echo "Detected variant: $VARIANT"

          case "$VARIANT" in
            client-preview) REDIST_DIR="redist/redist-client-preview" ;;
            server-preview) REDIST_DIR="redist/redist-server-preview" ;;
            client-preview-old) REDIST_DIR="redist/redist-client-preview-old" ;;
            server-preview-old) REDIST_DIR="redist/redist-server-preview-old" ;;
            client) REDIST_DIR="redist/redist-client" ;;
            server) REDIST_DIR="redist/redist-server" ;;
            client-publicized) REDIST_DIR="redist/redist-client-publicized" ;;
            server-publicized) REDIST_DIR="redist/redist-server-publicized" ;;
            client-preview-publicized) REDIST_DIR="redist/redist-client-preview-publicized" ;;
            server-preview-publicized) REDIST_DIR="redist/redist-server-preview-publicized" ;;
            *) 
              echo "Unknown variant: $VARIANT"
              exit 1
              ;;
          esac

      - name: Enable PR automerge
        if: success() && env.ALLOW_AUTO_MERGE_REDIST_PR == 'true' && github.actor == 'rocketmodfixadmin'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Auto-approve PR
        if: success() && env.ALLOW_AUTO_MERGE_REDIST_PR == 'true' && github.actor == 'rocketmodfixadmin'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          review-message: "Auto approved automated PR"
